version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: genpei
    container_name: genpei
    volumes:
      - /usr/bin/docker:/usr/bin/docker # for Ubuntu
      # - /usr/local/bin/docker:/usr/local/bin/docker # for MacOS
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp # for cwltool
      # Mounting PWD in the container for cwltool
      - ${PWD}:${PWD}
    environment:
      - GENPEI_HOST=0.0.0.0
      - GENPEI_PORT=8080
      - GENPEI_DEBUG=True
    ports:
      - 8080:8080
    restart: always
    working_dir: ${PWD}
    command: ["/bin/bash", "./entrypoint.dev.sh"]
