version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: genpei
    container_name: genpei
    volumes:
      - /usr/bin/docker:/usr/bin/docker # for Ubuntu
      # - /usr/local/bin/docker:/usr/local/bin/docker # for MacOS
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp # for cwltool
      - ${PWD}/data:/opt/genpei/data
      - ${PWD}/run:/opt/genpei/run
      - ${PWD}/genpei:/opt/genpei/genpei
      - ${PWD}/tests:/opt/genpei/tests
    ports:
      - 8080:8080
    restart: always
    command: ["tail", "-f", "/dev/null"]
