version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: stayhome_wes
    container_name: stayhome_wes
    volumes:
      - /usr/bin/docker:/usr/bin/docker # for Ubuntu
      # - /usr/local/bin/docker:/usr/local/bin/docker # for MacOS
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp # for cwltool
      - ${PWD}/stayhome_wes:/opt/stayhome_wes/stayhome_wes
    ports:
      - 8080:8080
    restart: always
    command: ["tail", "-f", "/dev/null"]
