name: Lint and Style Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check with flake8
      run: |
        flake8 . --count --show-source --statistics
    - name: Check with isort
      run: |
        isort -c
    - name: Check with mypy
      run: |
        mypy --strict --ignore-missing-imports .
